"""add phone number

Revision ID: a82478a125d0
Revises: 67fe29087405
Create Date: 2021-11-17 17:47:38.341684

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'a82478a125d0'
down_revision = '67fe29087405'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
