name: Build and Deploy code
on: 
  push:
    branches:
     - "main"
  pull:
    branches:
      - "main"
jobs:
  job1:
    runs-on: ubuntu-latest
    steps:
      - name: pulling git repo
        uses: actions/checkout@v2
      - name: say hi to user
        run: echo "hello user"